# This workflow provisions Azure infrastructure using Terraform when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the necessary Terraform configuration files in your repository.
# 
# To configure this workflow:
#
# 1. Create an Azure Service Principal for Terraform. Follow the instructions at:
#    https://docs.microsoft.com/en-us/azure/developer/terraform/authenticate-to-azure
#
# 2. Create secrets in your repository for your Azure credentials. The required secrets are:
#    - AZURE_CLIENT_ID
#    - AZURE_CLIENT_SECRET
#    - AZURE_TENANT_ID
#    - AZURE_SUBSCRIPTION_ID
#
# 3. Optionally, adjust the `TERRAFORM_VERSION` and `TERRAFORM_WORKSPACE` environment variables below.
#
# For more information on GitHub Actions for Terraform: https://github.com/hashicorp/setup-terraform
name: Terraform Plan & Apply

on:
  workflow_dispatch:

env:
  TERRAFORM_VERSION: '1.9.2'           # Set this to the Terraform version to use
  TERRAFORM_WORKSPACE: 'default'       # Set this to your desired Terraform workspace (optional)

permissions:
  contents: read
  id-token: write  # Required for GitHub OIDC to authenticate with Azure

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      env: 
        ARM_ACCESS_KEY: ${{ secrets.STORAGE_ACCOUNT_ACCESS_KEY }}
      run: terraform init

    - name: Terraform Plan
      env: 
        ARM_ACCESS_KEY: ${{ secrets.STORAGE_ACCOUNT_ACCESS_KEY }}
        TF_VAR_vm_ssh_public_key: ${{ secrets.AZURE_VM_SSH_PUBLIC_KEY }}
      run: terraform plan

    - name: Terraform Apply
      env: 
        ARM_ACCESS_KEY: ${{ secrets.STORAGE_ACCOUNT_ACCESS_KEY }}
        TF_VAR_vm_ssh_public_key: ${{ secrets.AZURE_VM_SSH_PUBLIC_KEY }}
      run: terraform apply -auto-approve


